name: recipe_book
description: "A fully functional recipe book app in Flutter."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5  # For state management

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/Chicken_Biriyani.JPG
    - assets/Chicken_Curry.JPG
    - assets/Fish_Starter.JPG
    - assets/Icecream.JPG
    - assets/Shrimp_Starter.JPG
    - assets/Milkshake.JPG
